name: PortMaster Release

on:
  workflow_dispatch:
    inputs:
        branch:
          required: true
          type: string
        tag:
          required: true
          type: string
        description:
          required: false
          type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          sparse-checkout: |
            ports/cataclysm-dda
          fetch-depth: 1

      - name: Archive Folder
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          directory: "ports/cataclysm-dda"
          filename: "cataclysm-dda.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ inputs.branch }}-${{ inputs.tag }}"
          artifacts: "ports/cataclysm-dda/cataclysm-dda.zip"
          body: ${{ inputs.description }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
