name: Pull Request Check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: test
          sparse-checkout: |
            releases
          fetch-depth: 1

      - name: Extract
        uses: ihiroky/extract-action@v1
        with:
          file_path: releases/data.zip
          extract_dir: ports/cataclysm-dda/cataclysm-dda
