name: Pull Request Check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: test
          sparse-checkout: |
            releases
          fetch-depth: 1

      - name: Unzip Archive
        uses: TonyBogdanov/zip@1.0
        with:
            args: unzip -qq ./releases/data.zip -d ./ports/cataclysm-dda/cataclysm-dda
