name: PortMaster Release

on:
  workflow_dispatch:
    inputs:
        branch:
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          sparse-checkout: |
            releases
            ports/cataclysm-dda/cataclysm-dda
          fetch-depth: 1

      - name: Extract
        uses: ihiroky/extract-action@v1
        with:
          file_path: releases/cataclysm-tiles.zip
          extract_dir: ports/cataclysm-dda/cataclysm-dda
          verbose: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: ${{ inputs.branch }}
          title: Update Binary
          add-paths: |
            ports/cataclysm-dda/cataclysm-dda
